### ISSUE TITLE
Does not work again

### ISSUE THREAD

**Issue by xFGhoul** [uintdev/Discord-Cache-Dump#4]
hey, this is a cool project but I tried it and it does not work. any reason as to why?

![cmd_eQatlvoemj](https://github.com/uintdev/Discord-Cache-Dump/assets/70284239/90405fc2-4db4-49fa-8565-657705cbaec8)

**Comment by uintdev** [comment]
I was wondering if it still even worked (with how things tend to change up). I think we found our answer.
I see what the issue might be. Digging into it.

**Comment by uintdev** [comment]
Released v1.2.4, which should address the issue. If it works (or doesn't), please let me know.

**Comment by xFGhoul** [comment]
it does work, though `data_3` seems to not be unpacked

**Comment by uintdev** [comment]
Generally, this tool is mainly focused on the cache files that would normally consist of individual files. The `data_` files would be a very different thing in this case (`binwalk` might be of some use when it comes to extracting part of it).

**Comment by uintdev** [comment]
As the core issue had been resolved as of v1.2.4, I will be closing this issue.
