### ISSUE TITLE
Cannot find Flatpak discord cache

### ISSUE THREAD

**Issue by ditt0132** [uintdev/Discord-Cache-Dump#6]
I installed discord with Flatpak, and this app cannot find cache in flatpak discord

Flatpak discord cache location: ~/.var/app/com.discordapp.Discord/config/discord/Cache/Cache_Data

**Comment by uintdev** [comment]
Flatpak support has now been added as of commit 3425521. This is behind the `--flatpak` or `-f` flag. The new change is available in the newly released v1.3.0 build.

**Comment by uintdev** [comment]
Closing under the assumption that the issue had been resolved. This was tested with a Steam Deck under SteamOS, as it makes use of Flatpak.
